name = "ks-foundations-of-inference-lean"
version = "0.1.0"
releaseRepo = "https://github.com/zariuq/ks-foundations-of-inference"
preferReleaseBuild = true
defaultTargets = ["KnuthSkilling"]
weakLeanArgs = ["-j", "1"]

[[lean_lib]]
name = "KnuthSkilling"

[[lean_lib]]
name = "Algebra"

[[lean_lib]]
name = "Computability"

[[lean_lib]]
name = "InformationTheory"

[[lean_lib]]
name = "Logic"

[[lean_lib]]
name = "ProbabilityTheory"

[[lean_lib]]
name = "UniversalAI"

[[require]]
name = "ordered_semigroups"
git = "https://github.com/zariuq/OrderedSemigroups.git"
rev = "dd82826dfce02bedabbad75734e4f055939369f6"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"
