import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.BenV2Theorem1
import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.CStrict0Fails
import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.FreeMonoidNoSeparation
import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.GoertzelLemma7
import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.KSSeparationNotDerivable
import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.NewAtomCommutesNotDerivable
import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.NoFiniteModel
import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.ProductFailsSeparation
import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.RankObstruction
import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.RankObstructionLinear
import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.SemidirectNoSeparation
import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.StrictGap
import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.ZQuantizedBEmpty
import Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.ZQuantizedBNonempty

/-!
# Knuth–Skilling: Counterexamples (Build Target)

This module imports the full suite of formal counterexamples used to clarify which hypotheses
are necessary for the Knuth–Skilling representation theorem development.

Build this file to compile the entire counterexample suite in one go:

```bash
ulimit -Sv 6291456
cd lean-projects/mettapedia
export LAKE_JOBS=1
nice -n 19 lake build Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Counterexamples.All
```

Exploration notes and failed model attempts live separately under
`Mettapedia.ProbabilityTheory.KnuthSkilling.RepresentationTheorem.Explorations`.
-/

